services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend: 
