services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'P!@#$$%^&*()'
      POSTGRES_DB: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend: 
